services:

  db1:
    image: mysql:8.0
    container_name: db1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: noe123
      MYSQL_DATABASE: comicsdb
    volumes:
      - db1_data:/var/lib/mysql
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal_net
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -pnoe123 -e 'SELECT 1;' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 60s

  db2:
    image: mysql:8.0
    container_name: db2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: noe123
      MYSQL_DATABASE: comicsdb
    volumes:
      - db2_data:/var/lib/mysql
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal_net
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -pnoe123 -e 'SELECT 1;' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 60s

  db3:
    image: mysql:8.0
    container_name: db3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: noe123
      MYSQL_DATABASE: comicsdb
    volumes:
      - db3_data:/var/lib/mysql
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal_net
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -pnoe123 -e 'SELECT 1;' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 60s

  haproxy_db:
    build:
      context: ./haproxy
      dockerfile: Dockerfile
    container_name: haproxy_db
    restart: always
    ports:
      - "3307:3307"
      - "8404:8404"
    depends_on:
      db1:
        condition: service_healthy
      db2:
        condition: service_healthy
      db3:
        condition: service_healthy
    networks:
      - internal_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "9090:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - internal_net

volumes:
  db1_data:
  db2_data:
  db3_data:

networks:
  internal_net:

