version: "3.9"

services:
  php:
    image: php:8.2-fpm
    container_name: php-fpm
    command: bash -c "docker-php-ext-install pdo pdo_mysql && php-fpm"
    volumes:
      - ./app:/var/www/html
    networks:
      - frontend_net

  web1:
    image: nginx:latest
    hostname: web1
    container_name: web1
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend_net
    depends_on:
      - php

  web2:
    image: nginx:latest
    hostname: web2
    container_name: web2
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend_net
    depends_on:
      - php

  web3:
    image: nginx:latest
    hostname: web3
    container_name: web3
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend_net
    depends_on:
      - php

  haproxy:
    image: haproxy:2.6
    container_name: haproxy
    ports:
      - "8085:80"
      - "8404:8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - frontend_net
    depends_on:
      - web1
      - web2
      - web3

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    ports:
      - "9090:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - frontend_net

networks:
  frontend_net:
    driver: bridge

