version: "3.9"

services:

  db1:
    image: mysql:8.0
    container_name: db1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: noe123
      MYSQL_DATABASE: comicsdb
    volumes:
      - db1_data:/var/lib/mysql
    networks:
      - internal_net

  db2:
    image: mysql:8.0
    container_name: db2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: noe123
      MYSQL_DATABASE: comicsdb
    volumes:
      - db2_data:/var/lib/mysql
    networks:
      - internal_net

  db3:
    image: mysql:8.0
    container_name: db3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: noe123
      MYSQL_DATABASE: comicsdb
    volumes:
      - db3_data:/var/lib/mysql
    networks:
      - internal_net

  haproxy_db:
    image: haproxy:latest
    container_name: haproxy_db
    ports:
      - "3307:3307"
    volumes:
      - ./haproxy/haproxy-db.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - db1
      - db2
      - db3
    networks:
      - internal_net

volumes:
  db1_data:
  db2_data:
  db3_data:

networks:
  internal_net:
